<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <sectionGroup name="ProppFrexx">
      <section name="DRAirliteMAP" type="System.Configuration.NameValueSectionHandler, System, Culture=neutral, Custom=null" />
    </sectionGroup>
  </configSections>
  <ProppFrexx>
    <DRAirliteMAP>
      <add key="0" value="104|4|1|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_PLAY_A" />
      <add key="1" value="104|5|1|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_PLAY_B" />
      <add key="2" value="104|6|1|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_PLAY_C" />
      <add key="3" value="104|6|0|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_EJECTNOFADE_C" />
      <add key="4" value="104|5|0|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_EJECTNOFADE_B" />
      <add key="5" value="104|4|0|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_EJECTNOFADE_A" />
      <add key="6" value="106|4|0|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_EJECTNOFADE_A" />
      <add key="7" value="106|6|0|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_EJECTNOFADE_C" />
      <add key="8" value="106|5|0|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_EJECTNOFADE_B" />
      <add key="9" value="102|1|1|MIXER_OUTPUT_MUTE_ON PFL" />
      <add key="10" value="102|1|0|MIXER_OUTPUT_MUTE_OFF PFL" />
      <add key="11" value="101|1|1|PLS_CURRENT_AUTOPLAY_ON" />
      <add key="12" value="101|1|0|PLS_CURRENT_AUTOPLAY_OFF" />
      <add key="13" value="97|4|1|PLS_CURRENT_PLAYER_A_PFL" />
      <add key="14" value="97|4|0|PLS_CURRENT_PFL_STOP " />
      <add key="15" value="97|5|1|PLS_CURRENT_PLAYER_B_PFL" />
      <add key="16" value="97|5|0|PLS_CURRENT_PFL_STOP" />
      <add key="17" value="97|6|1|PLS_CURRENT_PLAYER_C_PFL" />
      <add key="18" value="97|6|0|PLS_CURRENT_PFL_STOP" />
      <add key="19" value="106|4|1|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_PLAY_A" />
      <add key="20" value="106|5|1|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_PLAY_B" />
      <add key="21" value="106|6|1|EXEC_COMMAND2 ${autoplay}|Equals(0)|PLS_CURRENT_PLAY_C" />
      <add key="22" value="97|1|1|MIXER_OUTPUT_MUTE_ON PFL" />
      <add key="23" value="97|1|0|MIXER_OUTPUT_MUTE_OFF PFL" />
      <add key="24" value="97|2|1|MIXER_OUTPUT_MUTE_ON PFL" />
      <add key="25" value="97|3|1|MIXER_OUTPUT_MUTE_ON PFL" />
      <add key="26" value="97|2|0|MIXER_OUTPUT_MUTE_OFF PFL" />
      <add key="27" value="97|3|0|MIXER_OUTPUT_MUTE_OFF PFL" />
      <add key="30" value="34|1|1|CW1_PLAY_CART_1${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="31" value="34|2|1|CW1_PLAY_CART_2${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="32" value="34|3|1|CW1_PLAY_CART_3${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="33" value="34|4|1|CW1_PLAY_CART_4${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="34" value="34|5|1|CW1_PLAY_CART_5${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="35" value="34|6|1|CW1_PLAY_CART_6${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="36" value="34|7|1|CW1_PLAY_CART_7${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="37" value="34|8|1|CW1_PLAY_CART_8${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="38" value="106|7|1|MIXER_OUTPUT_MUTE_OFF PFL" />
      <add key="39" value="104|7|1|MIXER_OUTPUT_MUTE_OFF PFL" />
      <add key="40" value="97|7|0|PLS_CURRENT_PFL_STOP" />
      <add key="41" value="102|2|1|MIXER_OUTPUT_MUTE_ON PFL" />
      <add key="42" value="102|3|1|MIXER_OUTPUT_MUTE_ON PFL" />
      <add key="43" value="102|2|0|MIXER_OUTPUT_MUTE_OFF PFL" />
      <add key="44" value="102|3|0|MIXER_OUTPUT_MUTE_OFF PFL" />
      <add key="45" value="97|8|0|MIXER_OUTPUT_MUTE_OFF PFL" />
      <add key="46" value="97|8|1|MIXER_OUTPUT_MUTE_ON PFL" />
      <add key="47" value="111|1|1|MIXER_OUTPUT_MUTE_ON PFL${_NL}EXEC_SEND_DRAIRLITE_REMOTECUE 7|1${_NL}EXEC_SEND_DRAIRLITE_REMOTECUE 1|1" />
      <add key="48" value="111|1|0|MIXER_OUTPUT_MUTE_OFF PFL${_NL}EXEC_SEND_DRAIRLITE_REMOTECUERESET" />
      <add key="49" value="111|2|1|EXEC_SEND_DRAIRLITE_REMOTECUE 2|1" />
      <add key="50" value="111|3|1|EXEC_SEND_DRAIRLITE_REMOTECUE 3|1" />
      <add key="51" value="34|9|1|CW1_PLAY_CART_9${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="52" value="34|10|1|CW1_PLAY_CART_10${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="53" value="34|11|1|CW1_PLAY_CART_11${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="54" value="34|12|1|CW1_PLAY_CART_12${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="55" value="34|13|1|CW1_PLAY_CART_13${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="56" value="34|14|1|CW1_PLAY_CART_14${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="57" value="34|15|1|CW1_PLAY_CART_15${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="58" value="34|16|1|CW1_PLAY_CART_16${_NL}EXEC_SEND_DRAIRLITE_REMOTEON 7|1" />
      <add key="59" value="104|6|0|CW1_STOP_ALL ${_NL}MIXER_OUTPUT_MUTE_ON CW" />
    </DRAirliteMAP>
  </ProppFrexx>
</configuration>